version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: huynh
      MYSQL_DATABASE: docker
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  apiblog:
    image: apiblog
    build: .
    container_name: apiblog
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/blogsystemdb?createDatabaseIfNotExist=true
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: huynh
      SIGNER_KEY: Z90zsVhnvZB0snKg2ntwlh8RDn3TH23YsSZey6BrPcSeaFBj1AUJE4zc06F3U0i3
      USERNAME_ADMIN: huynhdz
      PASSWORD_ADMIN: huynhdz
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
