spring:
  application:
    name: APIBlog
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/blogsystemdb}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:huynh}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active:
    - prod
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html

