spring:
  application:
    name: APIMobileStore
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/blogsystemdb?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:huynh}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  signerKey: qL">!:j[qhkRR9"l+;1kfT/ye5d<Y"R:VTA[!Qt#zQmbIPlmQ"/mHjVdz);zuv`
  expirationTime: 1
account:
  admin:
    username: admin
    password: admin
